from __future__ import annotations

MESSAGE_FLAG_CROSSPOSTED = 1 << 0
MESSAGE_FLAG_IS_CROSSPOST = 1 << 1
MESSAGE_FLAG_SUPPRESS_EMBEDS = 1 << 2
MESSAGE_FLAG_SOURCE_MESSAGE_DELETED = 1 << 3
MESSAGE_FLAG_SUPPRESS_NOTIFICATIONS = 1 << 12
MESSAGE_FLAG_IS_VOICE_MESSAGE = 1 << 13
MESSAGE_FLAG_HAS_SNAPSHOT = 1 << 14
MESSAGE_FLAG_IS_COMPONENTS_V2 = 1 << 15

PUBLIC_MESSAGE_CREATE_FLAGS = (
    MESSAGE_FLAG_SUPPRESS_EMBEDS
    | MESSAGE_FLAG_SUPPRESS_NOTIFICATIONS
    | MESSAGE_FLAG_IS_VOICE_MESSAGE
    | MESSAGE_FLAG_IS_COMPONENTS_V2
)
PUBLIC_MESSAGE_EDIT_FLAGS = MESSAGE_FLAG_SUPPRESS_EMBEDS | MESSAGE_FLAG_IS_COMPONENTS_V2


def inferred_message_shape_flags(*, voice_message: bool, components_v2: bool) -> int:
    return (MESSAGE_FLAG_IS_VOICE_MESSAGE if voice_message else 0) | (
        MESSAGE_FLAG_IS_COMPONENTS_V2 if components_v2 else 0
    )
