[package]
name = "kaede-audio"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
cpal.workspace = true
crossbeam-queue.workspace = true
parking_lot.workspace = true
serde.workspace = true
thiserror.workspace = true
tracing.workspace = true

[lints]
workspace = true
