from __future__ import annotations

import json
import os
from pathlib import Path

from app.core.close_codes import GatewayCloseCode
from app.core.gateway_ops import EVENT_NAMES, PROTOCOL_VERSION, GatewayOp
from app.core.permissions import PERMISSION_METADATA, Permission

BACKEND_ROOT = Path(__file__).resolve().parents[1]
REPO_ROOT = BACKEND_ROOT.parent
OUTPUT = Path(
    os.environ.get(
        "KAEDE_GENERATED_OUTPUT",
        str(REPO_ROOT / "frontend" / "src" / "lib" / "generated"),
    )
)


def enum_ts(name: str, values: list[tuple[str, int]]) -> str:
    body = "\n".join(f"  {key} = {value}," for key, value in values)
    return f"export enum {name} {{\n{body}\n}}\n"


def render() -> dict[str, str]:
    ops = "// Generated by backend/scripts/generate_protocol.py; do not edit.\n"
    ops += f"export const PROTOCOL_VERSION = {PROTOCOL_VERSION} as const;\n\n"
    ops += enum_ts("GatewayOp", [(item.name, item.value) for item in GatewayOp])
    ops += "\n" + enum_ts(
        "GatewayCloseCode", [(item.name, item.value) for item in GatewayCloseCode]
    )
    ops += "\nexport const EVENT_NAMES = [\n"
    ops += "\n".join(f"  '{event}'," for event in EVENT_NAMES)
    ops += "\n] as const;\nexport type EventName = (typeof EVENT_NAMES)[number];\n"

    permissions = "// Generated by backend/scripts/generate_protocol.py; do not edit.\n"
    permissions += "export const Permission = {\n"
    permissions += "\n".join(f"  {item.name}: {item.value}n," for item in Permission)
    permissions += "\n} as const;\n"
    permissions += (
        "\nexport type PermissionDanger = 'normal' | 'elevated' | 'dangerous' | 'critical';\n"
    )
    permissions += "export type PermissionMetadata = {\n"
    permissions += "  permission: keyof typeof Permission;\n"
    permissions += "  bit: bigint;\n  label: string;\n  description: string;\n"
    permissions += "  group: string;\n  resourceScopes: readonly string[];\n"
    permissions += "  channelTypes: readonly number[];\n"
    permissions += "  dependencies: readonly (keyof typeof Permission)[];\n"
    permissions += "  danger: PermissionDanger;\n};\n"
    permissions += "\nexport const PERMISSION_METADATA = [\n"
    for item in PERMISSION_METADATA:
        permissions += "  {\n"
        permissions += f"    permission: '{item.permission.name}',\n"
        permissions += f"    bit: {item.permission.value}n,\n"
        permissions += f"    label: {json.dumps(item.label)},\n"
        permissions += f"    description: {json.dumps(item.description)},\n"
        permissions += f"    group: {json.dumps(item.group)},\n"
        permissions += f"    resourceScopes: {json.dumps(item.resource_scopes)},\n"
        permissions += f"    channelTypes: {json.dumps(item.channel_types)},\n"
        dependencies = [dependency.name for dependency in item.dependencies]
        permissions += f"    dependencies: {json.dumps(dependencies)},\n"
        permissions += f"    danger: '{item.danger}',\n"
        permissions += "  },\n"
    permissions += "] as const satisfies readonly PermissionMetadata[];\n"
    return {"ops.ts": ops, "permissions.ts": permissions}


def main() -> None:
    OUTPUT.mkdir(parents=True, exist_ok=True)
    for filename, content in render().items():
        (OUTPUT / filename).write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
