// Generated by backend/scripts/generate_protocol.py; do not edit.
const protocolVersion = 1;

const prioritySpeakerTopic = "kaede.priority-speaker.v1";
const prioritySpeakerInactivePayload = <int>[0];
const prioritySpeakerActivePayload = <int>[1];

const permissionSchema = "kaede-permissions-v1";

enum GatewayOp {
  dispatch(0),
  heartbeat(1),
  identify(2),
  presenceUpdate(3),
  voiceStateUpdate(4),
  resume(6),
  reconnect(7),
  requestMembers(8),
  invalidSession(9),
  hello(10),
  heartbeatAck(11),
  subscribeMemberList(12),
  requestSoundboardSounds(31),
  requestChannelInfo(43),
  ;

  const GatewayOp(this.value);
  final int value;
}

enum GatewayCloseCode {
  unknownError(4000),
  unknownOpcode(4001),
  decodeError(4002),
  notAuthenticated(4003),
  authenticationFailed(4004),
  alreadyAuthenticated(4005),
  invalidSequence(4006),
  rateLimited(4008),
  sessionTimedOut(4009),
  ;

  const GatewayCloseCode(this.value);
  final int value;
}

const eventNames = <String>{
  "READY",
  "RESUMED",
  "MESSAGE_CREATE",
  "MESSAGE_UPDATE",
  "MESSAGE_DELETE",
  "MESSAGE_DELETE_BULK",
  "MESSAGE_SEND_REJECTED",
  "MESSAGE_DELIVERY_UPDATE",
  "MESSAGE_REACTION_ADD",
  "MESSAGE_REACTION_REMOVE",
  "MESSAGE_REACTION_REMOVE_ALL",
  "MESSAGE_REACTION_REMOVE_EMOJI",
  "MESSAGE_PIN_UPDATE",
  "MESSAGE_POLL_VOTE_ADD",
  "MESSAGE_POLL_VOTE_REMOVE",
  "ATTACHMENT_UPDATE",
  "DM_OPEN_REJECTED",
  "CHANNEL_CREATE",
  "CHANNEL_UPDATE",
  "CHANNEL_DELETE",
  "CHANNEL_PINS_UPDATE",
  "CHANNEL_INFO",
  "CHANNEL_ACCESS_GRANTED",
  "CHANNEL_ACCESS_REVOKED",
  "CHANNEL_PERMISSION_UPDATE",
  "THREAD_CREATE",
  "THREAD_UPDATE",
  "THREAD_DELETE",
  "THREAD_LIST_SYNC",
  "THREAD_MEMBER_UPDATE",
  "THREAD_MEMBERS_UPDATE",
  "TRACKER_BOARD_UPDATE",
  "TRACKER_LANE_CREATE",
  "TRACKER_LANE_UPDATE",
  "TRACKER_LANE_DELETE",
  "TRACKER_TASK_CREATE",
  "TRACKER_TASK_UPDATE",
  "TRACKER_TASK_DELETE",
  "GUILD_CREATE",
  "GUILD_UPDATE",
  "GUILD_DELETE",
  "GUILD_ROLE_CREATE",
  "GUILD_ROLE_UPDATE",
  "GUILD_ROLE_DELETE",
  "GUILD_EMOJI_CREATE",
  "GUILD_EMOJI_UPDATE",
  "GUILD_EMOJI_DELETE",
  "GUILD_EMOJIS_UPDATE",
  "GUILD_STICKER_CREATE",
  "GUILD_STICKER_UPDATE",
  "GUILD_STICKER_DELETE",
  "GUILD_STICKERS_UPDATE",
  "GUILD_MEMBER_ADD",
  "GUILD_MEMBER_UPDATE",
  "GUILD_MEMBER_REMOVE",
  "GUILD_MEMBERS_PRUNED",
  "GUILD_MEMBERS_CHUNK",
  "GUILD_MEMBER_LIST_UPDATE",
  "GUILD_BAN_ADD",
  "GUILD_BAN_REMOVE",
  "GUILD_AUDIT_LOG_ENTRY_CREATE",
  "GUILD_INTEGRATIONS_UPDATE",
  "APPLICATION_COMMAND_PERMISSIONS_UPDATE",
  "INTEGRATION_CREATE",
  "INTEGRATION_UPDATE",
  "INTEGRATION_DELETE",
  "WEBHOOKS_UPDATE",
  "INVITE_CREATE",
  "INVITE_DELETE",
  "GUILD_SCHEDULED_EVENT_CREATE",
  "GUILD_SCHEDULED_EVENT_UPDATE",
  "GUILD_SCHEDULED_EVENT_DELETE",
  "GUILD_SCHEDULED_EVENT_USER_ADD",
  "GUILD_SCHEDULED_EVENT_USER_REMOVE",
  "STAGE_INSTANCE_CREATE",
  "STAGE_INSTANCE_UPDATE",
  "STAGE_INSTANCE_DELETE",
  "GUILD_SOUNDBOARD_SOUND_CREATE",
  "GUILD_SOUNDBOARD_SOUND_UPDATE",
  "GUILD_SOUNDBOARD_SOUND_DELETE",
  "GUILD_SOUNDBOARD_SOUNDS_UPDATE",
  "AUTO_MODERATION_RULE_CREATE",
  "AUTO_MODERATION_RULE_UPDATE",
  "AUTO_MODERATION_RULE_DELETE",
  "AUTO_MODERATION_ACTION_EXECUTION",
  "BOT_INSTALLATION_CREATE",
  "BOT_INSTALLATION_UPDATE",
  "BOT_INSTALLATION_DELETE",
  "GUILD_AVAILABILITY_UPDATE",
  "GUILD_NAVIGATION_UPDATE",
  "GUILD_HISTORY_SYNC_UPDATE",
  "PRESENCE_UPDATE",
  "TYPING_START",
  "VOICE_STATE_UPDATE",
  "VOICE_CHANNEL_EFFECT_SEND",
  "VOICE_CHANNEL_STATUS_UPDATE",
  "VOICE_CHANNEL_START_TIME_UPDATE",
  "VOICE_CHANNEL_MOVE",
  "VOICE_TOKEN",
  "READ_STATE_UPDATE",
  "USER_UPDATE",
  "FEDERATION_PEER_STATUS",
  "INTERACTION_CREATE",
  "INTERACTION_RESPONSE_CREATE",
  "INTERACTION_RESPONSE_UPDATE",
  "INTERACTION_RESPONSE_DELETE",
  "CALL_CREATE",
  "CALL_RING",
  "CALL_ACCEPT",
  "CALL_DECLINE",
  "CALL_END",
};

const botIntentNames = <String>{
  "guilds",
  "guild_members",
  "guild_moderation",
  "guild_expressions",
  "guild_integrations",
  "guild_webhooks",
  "guild_invites",
  "guild_voice_states",
  "guild_presences",
  "guild_messages",
  "guild_message_reactions",
  "guild_message_typing",
  "direct_messages",
  "direct_message_reactions",
  "direct_message_typing",
  "message_content",
  "guild_scheduled_events",
  "auto_moderation_configuration",
  "auto_moderation_execution",
  "guild_message_polls",
  "direct_message_polls",
  "interactions",
  "guild_tasks",
  "voice_states",
  "message_reactions",
  "guild_typing",
};

const botIntentAliases = <String, String>{
  "voice_states": "guild_voice_states",
  "message_reactions": "guild_message_reactions",
  "guild_typing": "guild_message_typing",
};

abstract final class Permission {
  static const createInvite = 1;
  static const kickMembers = 2;
  static const banMembers = 4;
  static const administrator = 8;
  static const manageChannels = 16;
  static const manageGuild = 32;
  static const addReactions = 64;
  static const viewAuditLog = 128;
  static const prioritySpeaker = 256;
  static const viewChannel = 1024;
  static const sendMessages = 2048;
  static const sendTtsMessages = 4096;
  static const manageMessages = 8192;
  static const embedLinks = 16384;
  static const attachFiles = 32768;
  static const readMessageHistory = 65536;
  static const mentionEveryone = 131072;
  static const useExternalEmojis = 262144;
  static const connect = 1048576;
  static const speak = 2097152;
  static const muteMembers = 4194304;
  static const deafenMembers = 8388608;
  static const moveMembers = 16777216;
  static const useVad = 33554432;
  static const changeNickname = 67108864;
  static const manageNicknames = 134217728;
  static const manageRoles = 268435456;
  static const manageWebhooks = 536870912;
  static const manageEmojis = 1073741824;
  static const stream = 2147483648;
  static const useApplicationCommands = 4294967296;
  static const requestToSpeak = 8589934592;
  static const manageThreads = 17179869184;
  static const createPublicThreads = 34359738368;
  static const createPrivateThreads = 68719476736;
  static const sendMessagesInThreads = 274877906944;
  static const manageEvents = 549755813888;
  static const moderateMembers = 1099511627776;
  static const banInstances = 2199023255552;
  static const useSoundboard = 8796093022208;
  static const createGuildExpressions = 17592186044416;
  static const createEvents = 35184372088832;
  static const useExternalSounds = 70368744177664;
  static const sendVoiceMessages = 140737488355328;
  static const setVoiceChannelStatus = 281474976710656;
  static const sendPolls = 562949953421312;
  static const useExternalApps = 1125899906842624;
  static const pinMessages = 2251799813685248;
  static const bypassSlowmode = 4503599627370496;
  static const createTrackerTasks = 9007199254740992;
  static const editOwnTrackerTasks = 18014398509481984;
  static const manageTrackerTasks = 36028797018963968;
  static const assignTrackerTasks = 72057594037927936;
  static const manageTracker = 144115188075855872;
  static const useExternalStickers = 288230376151711744;
  static const createInstantInvite = 1;
  static const manageGuildExpressions = 1073741824;
  static const manageAutoModeration = 32;
}

enum PermissionDanger { normal, elevated, dangerous, critical }

class PermissionMetadata {
  const PermissionMetadata({
    required this.name,
    required this.bit,
    required this.label,
    required this.description,
    required this.group,
    required this.resourceScopes,
    required this.channelTypes,
    required this.dependencies,
    required this.danger,
  });

  final String name;
  final int bit;
  final String label;
  final String description;
  final String group;
  final List<String> resourceScopes;
  final List<int> channelTypes;
  final List<int> dependencies;
  final PermissionDanger danger;
}

const permissionMetadata = <PermissionMetadata>[
  PermissionMetadata(
    name: "CREATE_INVITE",
    bit: 1,
    label: "Create invites",
    description: "Create guild invitation links.",
    group: "General",
    resourceScopes: ["guild", "channel"],
    channelTypes: [0, 2, 4, 5, 10, 11, 12, 13, 15, 17],
    dependencies: <int>[],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "KICK_MEMBERS",
    bit: 2,
    label: "Kick members",
    description: "Remove lower-ranked members from the guild.",
    group: "Membership",
    resourceScopes: ["guild"],
    channelTypes: [],
    dependencies: <int>[],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "BAN_MEMBERS",
    bit: 4,
    label: "Ban members",
    description:
        "Ban lower-ranked members and optionally remove their messages.",
    group: "Membership",
    resourceScopes: ["guild"],
    channelTypes: [],
    dependencies: <int>[],
    danger: PermissionDanger.dangerous,
  ),
  PermissionMetadata(
    name: "ADMINISTRATOR",
    bit: 8,
    label: "Administrator",
    description:
        "Bypass all channel permission overwrites and grant every permission.",
    group: "Advanced",
    resourceScopes: ["guild"],
    channelTypes: [],
    dependencies: <int>[],
    danger: PermissionDanger.critical,
  ),
  PermissionMetadata(
    name: "MANAGE_CHANNELS",
    bit: 16,
    label: "Manage channels",
    description: "Create, edit, reorder, and delete channels and categories.",
    group: "Management",
    resourceScopes: ["guild", "channel"],
    channelTypes: [0, 2, 4, 5, 10, 11, 12, 13, 15, 17],
    dependencies: <int>[],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "MANAGE_GUILD",
    bit: 32,
    label: "Manage guild",
    description: "Change guild settings and federation policy.",
    group: "Management",
    resourceScopes: ["guild"],
    channelTypes: [],
    dependencies: <int>[],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "ADD_REACTIONS",
    bit: 64,
    label: "Add reactions",
    description: "Add reactions to messages.",
    group: "Text",
    resourceScopes: ["channel"],
    channelTypes: [0, 2, 5, 10, 11, 12, 13, 15],
    dependencies: <int>[1024, 65536],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "VIEW_AUDIT_LOG",
    bit: 128,
    label: "View audit log",
    description: "View security-sensitive guild administration history.",
    group: "Management",
    resourceScopes: ["guild"],
    channelTypes: [],
    dependencies: <int>[],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "PRIORITY_SPEAKER",
    bit: 256,
    label: "Priority speaker",
    description:
        "Reduce other participants' volume while speaking in voice channels.",
    group: "Voice",
    resourceScopes: ["channel"],
    channelTypes: [2],
    dependencies: <int>[1048576, 2097152],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "VIEW_CHANNEL",
    bit: 1024,
    label: "View channel",
    description: "See a channel and its live activity.",
    group: "General",
    resourceScopes: ["channel"],
    channelTypes: [0, 2, 4, 5, 10, 11, 12, 13, 15, 17],
    dependencies: <int>[],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "SEND_MESSAGES",
    bit: 2048,
    label: "Send messages",
    description:
        "Send messages in channels and create posts in forum channels.",
    group: "Text",
    resourceScopes: ["channel"],
    channelTypes: [0, 2, 5, 13, 15],
    dependencies: <int>[1024],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "SEND_TTS_MESSAGES",
    bit: 4096,
    label: "Send text-to-speech messages",
    description: "Send messages that clients may read aloud.",
    group: "Text",
    resourceScopes: ["channel"],
    channelTypes: [0, 2, 5, 10, 11, 12, 13, 15],
    dependencies: <int>[1024, 2048],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "MANAGE_MESSAGES",
    bit: 8192,
    label: "Manage messages",
    description: "Delete and moderate other members' messages.",
    group: "Text",
    resourceScopes: ["channel"],
    channelTypes: [0, 2, 5, 10, 11, 12, 13, 15],
    dependencies: <int>[1024, 65536],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "EMBED_LINKS",
    bit: 16384,
    label: "Embed links",
    description: "Expand links into rich previews.",
    group: "Text",
    resourceScopes: ["channel"],
    channelTypes: [0, 2, 5, 10, 11, 12, 13, 15],
    dependencies: <int>[1024],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "ATTACH_FILES",
    bit: 32768,
    label: "Attach files",
    description: "Upload and attach files to messages.",
    group: "Text",
    resourceScopes: ["channel"],
    channelTypes: [0, 2, 5, 10, 11, 12, 13, 15],
    dependencies: <int>[1024],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "READ_MESSAGE_HISTORY",
    bit: 65536,
    label: "Read message history",
    description:
        "Read retained messages and receive permitted federated history.",
    group: "Text",
    resourceScopes: ["channel"],
    channelTypes: [0, 2, 5, 10, 11, 12, 13, 15],
    dependencies: <int>[1024],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "MENTION_EVERYONE",
    bit: 131072,
    label: "Mention everyone",
    description: "Notify broad guild or role audiences.",
    group: "Text",
    resourceScopes: ["channel"],
    channelTypes: [0, 2, 5, 10, 11, 12, 13, 15],
    dependencies: <int>[1024],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "USE_EXTERNAL_EMOJIS",
    bit: 262144,
    label: "Use external emoji",
    description: "Use emoji originating outside this guild.",
    group: "Text",
    resourceScopes: ["channel"],
    channelTypes: [0, 2, 5, 10, 11, 12, 13, 15],
    dependencies: <int>[1024],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "USE_EXTERNAL_STICKERS",
    bit: 288230376151711744,
    label: "Use external stickers",
    description: "Use stickers originating outside this guild.",
    group: "Text",
    resourceScopes: ["channel"],
    channelTypes: [0, 2, 5, 10, 11, 12, 13, 15],
    dependencies: <int>[1024],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "CONNECT",
    bit: 1048576,
    label: "Connect",
    description: "Join voice channels.",
    group: "Voice",
    resourceScopes: ["channel"],
    channelTypes: [2, 13],
    dependencies: <int>[1024],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "SPEAK",
    bit: 2097152,
    label: "Speak",
    description: "Publish microphone audio in voice channels.",
    group: "Voice",
    resourceScopes: ["channel"],
    channelTypes: [2],
    dependencies: <int>[1048576],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "MUTE_MEMBERS",
    bit: 4194304,
    label: "Mute members",
    description: "Server-mute other voice participants.",
    group: "Voice moderation",
    resourceScopes: ["channel"],
    channelTypes: [2, 13],
    dependencies: <int>[1048576],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "DEAFEN_MEMBERS",
    bit: 8388608,
    label: "Deafen members",
    description: "Server-deafen other voice participants.",
    group: "Voice moderation",
    resourceScopes: ["channel"],
    channelTypes: [2],
    dependencies: <int>[1048576],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "MOVE_MEMBERS",
    bit: 16777216,
    label: "Move members",
    description: "Move voice participants between channels.",
    group: "Voice moderation",
    resourceScopes: ["channel"],
    channelTypes: [2, 13],
    dependencies: <int>[1048576],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "USE_VAD",
    bit: 33554432,
    label: "Use voice activity",
    description:
        "Transmit with voice activity detection instead of push-to-talk.",
    group: "Voice",
    resourceScopes: ["channel"],
    channelTypes: [2],
    dependencies: <int>[2097152],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "CHANGE_NICKNAME",
    bit: 67108864,
    label: "Change nickname",
    description: "Change your own guild nickname.",
    group: "Membership",
    resourceScopes: ["guild"],
    channelTypes: [],
    dependencies: <int>[],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "MANAGE_NICKNAMES",
    bit: 134217728,
    label: "Manage nicknames",
    description: "Change lower-ranked members' nicknames.",
    group: "Membership",
    resourceScopes: ["guild"],
    channelTypes: [],
    dependencies: <int>[],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "MANAGE_ROLES",
    bit: 268435456,
    label: "Manage roles and permissions",
    description:
        "Manage lower roles, member role assignments, and channel overwrites.",
    group: "Management",
    resourceScopes: ["guild", "channel"],
    channelTypes: [0, 2, 4, 5, 10, 11, 12, 13, 15, 17],
    dependencies: <int>[],
    danger: PermissionDanger.critical,
  ),
  PermissionMetadata(
    name: "MANAGE_WEBHOOKS",
    bit: 536870912,
    label: "Manage webhooks",
    description: "Create, edit, rotate, and revoke channel webhooks.",
    group: "Management",
    resourceScopes: ["guild", "channel"],
    channelTypes: [0, 2, 5, 13, 15],
    dependencies: <int>[],
    danger: PermissionDanger.critical,
  ),
  PermissionMetadata(
    name: "MANAGE_EMOJIS",
    bit: 1073741824,
    label: "Manage emoji and stickers",
    description: "Create and remove guild emoji and stickers.",
    group: "Management",
    resourceScopes: ["guild"],
    channelTypes: [],
    dependencies: <int>[],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "STREAM",
    bit: 2147483648,
    label: "Share video and screen",
    description:
        "Publish camera video or screen shares in voice and Stage channels.",
    group: "Voice",
    resourceScopes: ["channel"],
    channelTypes: [2, 13],
    dependencies: <int>[1048576],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "USE_APPLICATION_COMMANDS",
    bit: 4294967296,
    label: "Use application commands",
    description:
        "Use slash commands and context menu commands from applications.",
    group: "Applications",
    resourceScopes: ["channel"],
    channelTypes: [0, 2, 5, 10, 11, 12, 13, 15, 17],
    dependencies: <int>[1024],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "REQUEST_TO_SPEAK",
    bit: 8589934592,
    label: "Request to speak",
    description: "Request speaker access in moderated voice channels.",
    group: "Voice",
    resourceScopes: ["channel"],
    channelTypes: [13],
    dependencies: <int>[1024, 1048576],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "MANAGE_THREADS",
    bit: 17179869184,
    label: "Manage threads and posts",
    description:
        "Rename, archive, lock, delete, and view private threads and forum posts.",
    group: "Thread management",
    resourceScopes: ["guild", "channel"],
    channelTypes: [0, 5, 10, 11, 12, 15],
    dependencies: <int>[1024],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "CREATE_PUBLIC_THREADS",
    bit: 34359738368,
    label: "Create public threads",
    description: "Create public and announcement threads.",
    group: "Threads",
    resourceScopes: ["channel"],
    channelTypes: [0, 5],
    dependencies: <int>[1024],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "CREATE_PRIVATE_THREADS",
    bit: 68719476736,
    label: "Create private threads",
    description: "Create private threads.",
    group: "Threads",
    resourceScopes: ["channel"],
    channelTypes: [0],
    dependencies: <int>[1024],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "SEND_MESSAGES_IN_THREADS",
    bit: 274877906944,
    label: "Send messages in threads",
    description:
        "Send messages in public, private, announcement, and forum-post threads.",
    group: "Threads",
    resourceScopes: ["channel"],
    channelTypes: [0, 5, 10, 11, 12, 15],
    dependencies: <int>[1024],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "MANAGE_EVENTS",
    bit: 549755813888,
    label: "Manage events",
    description: "Edit and cancel guild events created by other members.",
    group: "Management",
    resourceScopes: ["guild", "channel"],
    channelTypes: [2, 13],
    dependencies: <int>[],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "MODERATE_MEMBERS",
    bit: 1099511627776,
    label: "Timeout members",
    description: "Temporarily or indefinitely restrict lower-ranked members.",
    group: "Membership",
    resourceScopes: ["guild"],
    channelTypes: [],
    dependencies: <int>[],
    danger: PermissionDanger.dangerous,
  ),
  PermissionMetadata(
    name: "BAN_INSTANCES",
    bit: 2199023255552,
    label: "Ban federated instances",
    description: "Remove and block every member from a federated instance.",
    group: "Federation",
    resourceScopes: ["guild"],
    channelTypes: [],
    dependencies: <int>[],
    danger: PermissionDanger.critical,
  ),
  PermissionMetadata(
    name: "USE_SOUNDBOARD",
    bit: 8796093022208,
    label: "Use soundboard",
    description: "Play guild soundboard sounds in voice channels.",
    group: "Voice",
    resourceScopes: ["channel"],
    channelTypes: [2],
    dependencies: <int>[1024, 1048576, 2097152],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "CREATE_GUILD_EXPRESSIONS",
    bit: 17592186044416,
    label: "Create guild expressions",
    description: "Create guild emoji, stickers, and soundboard sounds.",
    group: "Management",
    resourceScopes: ["guild"],
    channelTypes: [],
    dependencies: <int>[],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "CREATE_EVENTS",
    bit: 35184372088832,
    label: "Create events",
    description: "Create guild events.",
    group: "Management",
    resourceScopes: ["guild", "channel"],
    channelTypes: [2, 13],
    dependencies: <int>[],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "USE_EXTERNAL_SOUNDS",
    bit: 70368744177664,
    label: "Use external sounds",
    description: "Play soundboard sounds originating outside this guild.",
    group: "Voice",
    resourceScopes: ["channel"],
    channelTypes: [2],
    dependencies: <int>[1024, 1048576, 2097152, 8796093022208],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "SEND_VOICE_MESSAGES",
    bit: 140737488355328,
    label: "Send voice messages",
    description:
        "Send recorded voice messages in text, voice, Stage, and thread chats.",
    group: "Text",
    resourceScopes: ["channel"],
    channelTypes: [0, 2, 5, 10, 11, 12, 13, 15],
    dependencies: <int>[1024],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "SET_VOICE_CHANNEL_STATUS",
    bit: 281474976710656,
    label: "Set voice channel status",
    description: "Set the displayed status for a voice channel.",
    group: "Voice",
    resourceScopes: ["channel"],
    channelTypes: [2],
    dependencies: <int>[1024, 1048576],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "SEND_POLLS",
    bit: 562949953421312,
    label: "Send polls",
    description: "Create polls in text, voice, Stage, and thread chats.",
    group: "Text",
    resourceScopes: ["channel"],
    channelTypes: [0, 2, 5, 10, 11, 12, 13, 15],
    dependencies: <int>[1024],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "USE_EXTERNAL_APPS",
    bit: 1125899906842624,
    label: "Use external apps",
    description:
        "Let user-installed apps that are not installed to this guild send public responses; otherwise their responses are private.",
    group: "Applications",
    resourceScopes: ["channel"],
    channelTypes: [0, 2, 5, 10, 11, 12, 13, 15, 17],
    dependencies: <int>[1024],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "PIN_MESSAGES",
    bit: 2251799813685248,
    label: "Pin messages",
    description: "Pin and unpin messages in text channels and threads.",
    group: "Text moderation",
    resourceScopes: ["channel"],
    channelTypes: [0, 5, 10, 11, 12, 15],
    dependencies: <int>[1024, 65536],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "BYPASS_SLOWMODE",
    bit: 4503599627370496,
    label: "Bypass slowmode",
    description: "Send messages and create posts without waiting for slowmode.",
    group: "Text",
    resourceScopes: ["channel"],
    channelTypes: [0, 2, 5, 10, 11, 12, 13, 15],
    dependencies: <int>[1024],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "CREATE_TRACKER_TASKS",
    bit: 9007199254740992,
    label: "Create tracker tasks",
    description: "Add tasks to tracker channels.",
    group: "Tracker",
    resourceScopes: ["channel"],
    channelTypes: [17],
    dependencies: <int>[1024],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "EDIT_OWN_TRACKER_TASKS",
    bit: 18014398509481984,
    label: "Edit own tracker tasks",
    description:
        "Edit, move, complete, and delete tasks you created or are assigned.",
    group: "Tracker",
    resourceScopes: ["channel"],
    channelTypes: [17],
    dependencies: <int>[1024],
    danger: PermissionDanger.normal,
  ),
  PermissionMetadata(
    name: "MANAGE_TRACKER_TASKS",
    bit: 36028797018963968,
    label: "Manage tracker tasks",
    description:
        "Edit, move, complete, and delete any task in tracker channels.",
    group: "Tracker moderation",
    resourceScopes: ["channel"],
    channelTypes: [17],
    dependencies: <int>[1024],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "ASSIGN_TRACKER_TASKS",
    bit: 72057594037927936,
    label: "Assign tracker tasks",
    description: "Assign and unassign other members on tracker tasks.",
    group: "Tracker moderation",
    resourceScopes: ["channel"],
    channelTypes: [17],
    dependencies: <int>[1024],
    danger: PermissionDanger.elevated,
  ),
  PermissionMetadata(
    name: "MANAGE_TRACKER",
    bit: 144115188075855872,
    label: "Manage tracker",
    description:
        "Change tracker settings and create, edit, reorder, or remove lanes.",
    group: "Tracker management",
    resourceScopes: ["channel"],
    channelTypes: [17],
    dependencies: <int>[1024],
    danger: PermissionDanger.elevated,
  ),
];
