"""bot administration and developer platform

Revision ID: 94397280832f
Revises: a63d9f2c4b10
Create Date: 2026-08-14 02:31:20.425715
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "94397280832f"
down_revision: str | None = "a63d9f2c4b10"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instance_audit_events",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("actor_id", sa.BigInteger(), nullable=True),
        sa.Column("actor_domain", sa.String(length=253), nullable=True),
        sa.Column("actor_kind", sa.String(length=16), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column("target_ref", sa.String(length=320), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column(
            "detail", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("trace_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "actor_kind IN ('user','admin','cli','service','system')",
            name=op.f("ck_instance_audit_events_actor_kind_value"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instance_audit_events")),
    )
    op.create_index(
        "ix_instance_audit_events_created",
        "instance_audit_events",
        ["created_at", "id"],
        unique=False,
    )
    op.create_index(
        "ix_instance_audit_events_target",
        "instance_audit_events",
        ["target_type", "target_ref"],
        unique=False,
    )
    op.create_table(
        "developer_teams",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("origin_domain", sa.String(length=253), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("personal", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(btrim(name)) BETWEEN 1 AND 100",
            name=op.f("ck_developer_teams_team_name_length"),
        ),
        sa.ForeignKeyConstraint(
            ["origin_domain"],
            ["instances.domain"],
            name=op.f("fk_developer_teams_origin_domain_instances"),
        ),
        sa.PrimaryKeyConstraint("id", "origin_domain", name=op.f("pk_developer_teams")),
    )
    op.create_table(
        "abuse_reports",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("reporter_id", sa.BigInteger(), nullable=False),
        sa.Column("reporter_domain", sa.String(length=253), nullable=False),
        sa.Column(
            "reporter_is_local", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("target_type", sa.String(length=24), nullable=False),
        sa.Column("target_ref", sa.String(length=320), nullable=False),
        sa.Column("category", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=2000), nullable=True),
        sa.Column("message_ref", sa.String(length=320), nullable=True),
        sa.Column(
            "evidence", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column(
            "encryption_mode", sa.String(length=16), server_default="plaintext", nullable=False
        ),
        sa.Column("status", sa.String(length=24), server_default="submitted", nullable=False),
        sa.Column("assigned_admin_id", sa.BigInteger(), nullable=True),
        sa.Column("assigned_admin_domain", sa.String(length=253), nullable=True),
        sa.Column("resolution", sa.String(length=2000), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "category IN ('spam','harassment','hate','sexual_content','violence','self_harm','impersonation','privacy','malware','illegal_content','other')",  # noqa: E501
            name=op.f("ck_abuse_reports_abuse_report_category_value"),
        ),
        sa.CheckConstraint(
            "encryption_mode IN ('plaintext','e2ee_metadata')",
            name=op.f("ck_abuse_reports_abuse_report_encryption_mode_value"),
        ),
        sa.CheckConstraint(
            "status IN ('submitted','triaged','in_review','awaiting_remote','needs_information','action_taken','closed_no_action','duplicate','reopened')",  # noqa: E501
            name=op.f("ck_abuse_reports_abuse_report_status_value"),
        ),
        sa.CheckConstraint(
            "target_type IN ('message','user','bot','application','guild','instance','invite')",
            name=op.f("ck_abuse_reports_abuse_report_target_type_value"),
        ),
        sa.CheckConstraint(
            "reporter_is_local", name=op.f("ck_abuse_reports_abuse_report_reporter_is_local")
        ),
        sa.ForeignKeyConstraint(
            ["reporter_id", "reporter_domain", "reporter_is_local"],
            ["users.id", "users.origin_domain", "users.is_local"],
            name=op.f("fk_abuse_reports_reporter_id_reporter_domain_reporter_is_local_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_abuse_reports")),
    )
    op.create_index(
        "ix_abuse_reports_queue", "abuse_reports", ["status", "created_at"], unique=False
    )
    op.create_table(
        "bot_applications",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("origin_domain", sa.String(length=253), nullable=False),
        sa.Column("team_id", sa.BigInteger(), nullable=False),
        sa.Column("team_domain", sa.String(length=253), nullable=False),
        sa.Column("bot_user_id", sa.BigInteger(), nullable=False),
        sa.Column("bot_user_domain", sa.String(length=253), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("icon_hash", sa.String(length=128), nullable=True),
        sa.Column("support_url", sa.String(length=2048), nullable=True),
        sa.Column("privacy_url", sa.String(length=2048), nullable=True),
        sa.Column("status", sa.String(length=24), server_default="draft", nullable=False),
        sa.Column("custody_mode", sa.String(length=16), server_default="managed", nullable=False),
        sa.Column("target_policy", sa.String(length=16), server_default="open", nullable=False),
        sa.Column(
            "default_scopes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "default_intents",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("default_permissions", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "e2ee_modes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='["interaction_only"]',
            nullable=False,
        ),
        sa.Column("manifest_generation", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("command_generation", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("revocation_generation", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "custody_mode IN ('managed','external')",
            name=op.f("ck_bot_applications_custody_mode_value"),
        ),
        sa.CheckConstraint(
            "status IN ('draft','active','review_required','suspended','deleting','deleted')",
            name=op.f("ck_bot_applications_bot_application_status_value"),
        ),
        sa.CheckConstraint(
            "target_policy IN ('open','allowlist','blocklist','local_only')",
            name=op.f("ck_bot_applications_bot_target_policy_value"),
        ),
        sa.CheckConstraint(
            "default_permissions >= 0 AND manifest_generation >= 1 AND command_generation >= 1 AND revocation_generation >= 1",  # noqa: E501
            name=op.f("ck_bot_applications_bot_application_positive_values"),
        ),
        sa.ForeignKeyConstraint(
            ["bot_user_id", "bot_user_domain"],
            ["users.id", "users.origin_domain"],
            name=op.f("fk_bot_applications_bot_user_id_bot_user_domain_users"),
        ),
        sa.ForeignKeyConstraint(
            ["origin_domain"],
            ["instances.domain"],
            name=op.f("fk_bot_applications_origin_domain_instances"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id", "team_domain"],
            ["developer_teams.id", "developer_teams.origin_domain"],
            name=op.f("fk_bot_applications_team_id_team_domain_developer_teams"),
        ),
        sa.PrimaryKeyConstraint("id", "origin_domain", name=op.f("pk_bot_applications")),
        sa.UniqueConstraint("bot_user_id", "bot_user_domain", name="uq_bot_application_user"),
    )
    op.create_index(
        "ix_bot_applications_team", "bot_applications", ["team_id", "team_domain"], unique=False
    )
    op.create_table(
        "developer_team_members",
        sa.Column("team_id", sa.BigInteger(), nullable=False),
        sa.Column("team_domain", sa.String(length=253), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("user_domain", sa.String(length=253), nullable=False),
        sa.Column("user_is_local", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("role", sa.String(length=24), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner','administrator','developer','security','analyst','support')",
            name=op.f("ck_developer_team_members_developer_team_member_role_value"),
        ),
        sa.CheckConstraint(
            "user_is_local",
            name=op.f("ck_developer_team_members_developer_team_member_user_is_local"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id", "team_domain"],
            ["developer_teams.id", "developer_teams.origin_domain"],
            name=op.f("fk_developer_team_members_team_id_team_domain_developer_teams"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "user_domain", "user_is_local"],
            ["users.id", "users.origin_domain", "users.is_local"],
            name=op.f("fk_developer_team_members_user_id_user_domain_user_is_local_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "team_id",
            "team_domain",
            "user_id",
            "user_domain",
            name=op.f("pk_developer_team_members"),
        ),
    )
    op.create_index(
        "ix_developer_team_members_user",
        "developer_team_members",
        ["user_id", "user_domain"],
        unique=False,
    )
    op.create_table(
        "instance_admin_grants",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("user_domain", sa.String(length=253), nullable=False),
        sa.Column("user_is_local", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("generation", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("granted_by_id", sa.BigInteger(), nullable=True),
        sa.Column("granted_by_domain", sa.String(length=253), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "role IN ('owner','administrator','trust_safety','bot_reviewer','operations','auditor')",  # noqa: E501
            name=op.f("ck_instance_admin_grants_admin_grant_role_value"),
        ),
        sa.CheckConstraint(
            "generation >= 1", name=op.f("ck_instance_admin_grants_admin_grant_generation_positive")
        ),
        sa.CheckConstraint(
            "user_is_local", name=op.f("ck_instance_admin_grants_admin_grant_user_is_local")
        ),
        sa.ForeignKeyConstraint(
            ["user_id", "user_domain", "user_is_local"],
            ["users.id", "users.origin_domain", "users.is_local"],
            name=op.f("fk_instance_admin_grants_user_id_user_domain_user_is_local_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_instance_admin_grants")),
        sa.UniqueConstraint("user_id", "user_domain", "role", name="uq_admin_grant_user_role"),
    )
    op.create_index(
        "ix_instance_admin_grants_active",
        "instance_admin_grants",
        ["user_id", "user_domain", "revoked_at"],
        unique=False,
    )
    op.create_table(
        "application_commands",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("application_id", sa.BigInteger(), nullable=False),
        sa.Column("application_domain", sa.String(length=253), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=True),
        sa.Column("guild_domain", sa.String(length=253), nullable=True),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=16), server_default="chat_input", nullable=False),
        sa.Column("definition", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("generation", sa.BigInteger(), nullable=False),
        sa.Column("state", sa.String(length=16), server_default="active", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "name ~ '^[a-z0-9_-]{1,32}$'",
            name=op.f("ck_application_commands_application_command_name_format"),
        ),
        sa.CheckConstraint(
            "state IN ('pending','active','superseded','failed')",
            name=op.f("ck_application_commands_application_command_state_value"),
        ),
        sa.CheckConstraint(
            "type IN ('chat_input','user','message')",
            name=op.f("ck_application_commands_application_command_type_value"),
        ),
        sa.CheckConstraint(
            "(guild_id IS NULL) = (guild_domain IS NULL)",
            name=op.f("ck_application_commands_command_guild_ref_complete"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id", "application_domain"],
            ["bot_applications.id", "bot_applications.origin_domain"],
            name=op.f("fk_application_commands_application_id_application_domain_bot_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_commands")),
        sa.UniqueConstraint(
            "application_id",
            "application_domain",
            "guild_id",
            "guild_domain",
            "type",
            "name",
            name="uq_application_command_scope_name",
        ),
    )
    op.create_table(
        "bot_credentials",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("application_id", sa.BigInteger(), nullable=False),
        sa.Column("application_domain", sa.String(length=253), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("token_hint", sa.String(length=20), nullable=False),
        sa.Column(
            "scopes", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "octet_length(token_hash) = 32",
            name=op.f("ck_bot_credentials_bot_credential_hash_length"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id", "application_domain"],
            ["bot_applications.id", "bot_applications.origin_domain"],
            name=op.f("fk_bot_credentials_application_id_application_domain_bot_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_credentials")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_bot_credentials_token_hash")),
    )
    op.create_index(
        "ix_bot_credentials_application",
        "bot_credentials",
        ["application_id", "application_domain"],
        unique=False,
    )
    op.create_table(
        "bot_install_templates",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("application_id", sa.BigInteger(), nullable=False),
        sa.Column("application_domain", sa.String(length=253), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.String(length=500), nullable=True),
        sa.Column(
            "scopes", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "intents", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("permissions", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "contexts",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default='["guild"]',
            nullable=False,
        ),
        sa.Column(
            "e2ee_mode", sa.String(length=24), server_default="interaction_only", nullable=False
        ),
        sa.Column("generation", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "e2ee_mode IN ('disabled','interaction_only','participant')",
            name=op.f("ck_bot_install_templates_bot_template_e2ee_mode_value"),
        ),
        sa.CheckConstraint(
            "slug ~ '^[a-z0-9][a-z0-9_-]{1,63}$'",
            name=op.f("ck_bot_install_templates_bot_template_slug_format"),
        ),
        sa.CheckConstraint(
            "permissions >= 0 AND generation >= 1",
            name=op.f("ck_bot_install_templates_bot_template_positive_values"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id", "application_domain"],
            ["bot_applications.id", "bot_applications.origin_domain"],
            name=op.f(
                "fk_bot_install_templates_application_id_application_domain_bot_applications"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_install_templates")),
        sa.UniqueConstraint(
            "application_id", "application_domain", "slug", name="uq_bot_template_slug"
        ),
    )
    op.create_table(
        "bot_installations",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("application_id", sa.BigInteger(), nullable=False),
        sa.Column("application_domain", sa.String(length=253), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=False),
        sa.Column("guild_domain", sa.String(length=253), nullable=False),
        sa.Column("bot_user_id", sa.BigInteger(), nullable=False),
        sa.Column("bot_user_domain", sa.String(length=253), nullable=False),
        sa.Column("installer_id", sa.BigInteger(), nullable=False),
        sa.Column("installer_domain", sa.String(length=253), nullable=False),
        sa.Column(
            "granted_scopes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "granted_intents",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("granted_permissions", sa.BigInteger(), server_default="0", nullable=False),
        sa.Column(
            "channel_restrictions",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("e2ee_mode", sa.String(length=24), server_default="disabled", nullable=False),
        sa.Column("grant_revision", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("status", sa.String(length=16), server_default="active", nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "e2ee_mode IN ('disabled','interaction_only','participant')",
            name=op.f("ck_bot_installations_bot_installation_e2ee_mode_value"),
        ),
        sa.CheckConstraint(
            "status IN ('active','suspended','revoked')",
            name=op.f("ck_bot_installations_bot_installation_status_value"),
        ),
        sa.CheckConstraint(
            "granted_permissions >= 0 AND grant_revision >= 1",
            name=op.f("ck_bot_installations_bot_installation_positive_values"),
        ),
        sa.ForeignKeyConstraint(
            ["bot_user_id", "bot_user_domain"],
            ["users.id", "users.origin_domain"],
            name=op.f("fk_bot_installations_bot_user_id_bot_user_domain_users"),
        ),
        sa.ForeignKeyConstraint(
            ["guild_id", "guild_domain"],
            ["guilds.id", "guilds.origin_domain"],
            name=op.f("fk_bot_installations_guild_id_guild_domain_guilds"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["installer_id", "installer_domain"],
            ["users.id", "users.origin_domain"],
            name=op.f("fk_bot_installations_installer_id_installer_domain_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_installations")),
        sa.UniqueConstraint(
            "application_id",
            "application_domain",
            "guild_id",
            "guild_domain",
            name="uq_bot_installation_app_guild",
        ),
    )
    op.create_index(
        "ix_bot_installations_guild",
        "bot_installations",
        ["guild_id", "guild_domain", "status"],
        unique=False,
    )
    op.create_table(
        "bot_workers",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("application_id", sa.BigInteger(), nullable=False),
        sa.Column("application_domain", sa.String(length=253), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column(
            "scopes", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "intents", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "target_domains",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("generation", sa.BigInteger(), server_default="1", nullable=False),
        sa.Column("session_limit", sa.Integer(), server_default="1", nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "generation >= 1 AND session_limit BETWEEN 1 AND 16",
            name=op.f("ck_bot_workers_bot_worker_limits"),
        ),
        sa.CheckConstraint(
            "octet_length(public_key) = 32",
            name=op.f("ck_bot_workers_bot_worker_public_key_length"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id", "application_domain"],
            ["bot_applications.id", "bot_applications.origin_domain"],
            name=op.f("fk_bot_workers_application_id_application_domain_bot_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_workers")),
        sa.UniqueConstraint(
            "application_id", "application_domain", "name", name="uq_bot_worker_name"
        ),
    )
    op.create_table(
        "bot_tokens",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.LargeBinary(length=32), nullable=False),
        sa.Column("application_id", sa.BigInteger(), nullable=False),
        sa.Column("application_domain", sa.String(length=253), nullable=False),
        sa.Column("worker_id", sa.BigInteger(), nullable=False),
        sa.Column("dpop_thumbprint", sa.String(length=128), nullable=True),
        sa.Column(
            "scopes", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "intents", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "expires_at > issued_at", name=op.f("ck_bot_tokens_bot_token_positive_lifetime")
        ),
        sa.CheckConstraint(
            "octet_length(token_hash) = 32", name=op.f("ck_bot_tokens_bot_token_hash_length")
        ),
        sa.ForeignKeyConstraint(
            ["worker_id"],
            ["bot_workers.id"],
            name=op.f("fk_bot_tokens_worker_id_bot_workers"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_bot_tokens_token_hash")),
    )
    op.create_index(
        "ix_bot_tokens_worker_expiry", "bot_tokens", ["worker_id", "expires_at"], unique=False
    )
    op.add_column(
        "users",
        sa.Column("account_type", sa.String(length=16), server_default="human", nullable=False),
    )
    op.drop_constraint(op.f("ck_users_local_auth_fields"), "users", type_="check")
    op.create_check_constraint("account_type_value", "users", "account_type IN ('human','bot')")
    op.create_check_constraint(
        "local_auth_fields",
        "users",
        "NOT is_local OR account_type = 'bot' OR password_hash IS NOT NULL",
    )
    op.create_check_constraint(
        "bot_has_no_human_auth_fields",
        "users",
        "account_type = 'human' OR (password_hash IS NULL AND email IS NULL "
        "AND email_verified_at IS NULL AND totp_secret_encrypted IS NULL)",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bot_tokens_worker_expiry", table_name="bot_tokens")
    op.drop_table("bot_tokens")
    op.drop_table("bot_workers")
    op.drop_index("ix_bot_installations_guild", table_name="bot_installations")
    op.drop_table("bot_installations")
    op.drop_table("bot_install_templates")
    op.drop_index("ix_bot_credentials_application", table_name="bot_credentials")
    op.drop_table("bot_credentials")
    op.drop_table("application_commands")
    op.drop_index("ix_instance_admin_grants_active", table_name="instance_admin_grants")
    op.drop_table("instance_admin_grants")
    op.drop_index("ix_developer_team_members_user", table_name="developer_team_members")
    op.drop_table("developer_team_members")
    op.drop_index("ix_bot_applications_team", table_name="bot_applications")
    op.drop_table("bot_applications")
    op.drop_index("ix_abuse_reports_queue", table_name="abuse_reports")
    op.drop_table("abuse_reports")
    op.drop_table("developer_teams")
    op.drop_index("ix_instance_audit_events_target", table_name="instance_audit_events")
    op.drop_index("ix_instance_audit_events_created", table_name="instance_audit_events")
    op.drop_table("instance_audit_events")
    op.execute("DELETE FROM users WHERE account_type = 'bot'")
    op.drop_constraint(op.f("ck_users_bot_has_no_human_auth_fields"), "users", type_="check")
    op.drop_constraint(op.f("ck_users_local_auth_fields"), "users", type_="check")
    op.drop_constraint(op.f("ck_users_account_type_value"), "users", type_="check")
    op.drop_column("users", "account_type")
    op.create_check_constraint(
        "local_auth_fields", "users", "NOT is_local OR password_hash IS NOT NULL"
    )
    # ### end Alembic commands ###
