"""initial v1 schema

Revision ID: e66205549616
Revises:
Create Date: 2026-07-12 22:27:30.653758
"""
from collections.abc import Sequence
from datetime import UTC, datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e66205549616'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

SNOWFLAKE_EPOCH_MS = 1_767_225_600_000


def _snowflake_bound(year: int, month: int) -> int:
    instant = datetime(year, month, 1, tzinfo=UTC)
    timestamp_ms = int(instant.timestamp() * 1_000)
    return (timestamp_ms - SNOWFLAKE_EPOCH_MS) << 22


def _create_message_partition(year: int, month: int, next_year: int, next_month: int) -> None:
    name = f"messages_{year:04d}_{month:02d}"
    lower = _snowflake_bound(year, month)
    upper = _snowflake_bound(next_year, next_month)
    op.execute(
        f"CREATE TABLE {name} PARTITION OF messages "
        f"FOR VALUES FROM ({lower}) TO ({upper})"
    )


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federation_inbox',
    sa.Column('origin_domain', sa.String(length=253), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='received', nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('origin_domain', 'event_id', name=op.f('pk_federation_inbox'))
    )
    op.create_table('instance_blocks',
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('include_subdomains', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("level IN ('silence','suspend')", name=op.f('ck_instance_blocks_block_level')),
    sa.PrimaryKeyConstraint('domain', name=op.f('pk_instance_blocks'))
    )
    op.create_table('instances',
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('is_self', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('software_version', sa.String(length=40), nullable=True),
    sa.Column('federation_mode', sa.String(length=16), server_default='open', nullable=False),
    sa.Column('current_key_id', sa.String(length=64), nullable=True),
    sa.Column('encrypted_private_key', sa.LargeBinary(), nullable=True),
    sa.Column('private_key_nonce', sa.LargeBinary(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT is_self OR (current_key_id IS NOT NULL AND encrypted_private_key IS NOT NULL AND private_key_nonce IS NOT NULL)', name=op.f('ck_instances_self_has_private_key')),
    sa.PrimaryKeyConstraint('domain', name=op.f('pk_instances')),
    sa.UniqueConstraint('domain', 'is_self', name='uq_instances_domain_is_self')
    )
    op.create_index('uq_instances_single_self', 'instances', ['is_self'], unique=True, postgresql_where=sa.text('is_self'))
    op.create_table('remote_media_cache',
    sa.Column('origin_domain', sa.String(length=253), nullable=False),
    sa.Column('attachment_id', sa.BigInteger(), nullable=False),
    sa.Column('variant', sa.String(length=32), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('scan_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('origin_domain', 'attachment_id', 'variant', name=op.f('pk_remote_media_cache'))
    )
    op.create_index('ix_remote_media_cache_eviction', 'remote_media_cache', ['last_accessed_at'], unique=False)
    op.create_table('dm_conversations',
    sa.Column('pair_key', sa.String(length=64), nullable=False),
    sa.Column('type', sa.String(length=16), server_default='direct', nullable=False),
    sa.Column('authority_domain', sa.String(length=253), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('origin_domain', sa.String(length=253), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('direct','group')", name=op.f('ck_dm_conversations_conversation_type')),
    sa.ForeignKeyConstraint(['authority_domain'], ['instances.domain'], name=op.f('fk_dm_conversations_authority_domain_instances')),
    sa.PrimaryKeyConstraint('id', 'origin_domain', name=op.f('pk_dm_conversations')),
    sa.UniqueConstraint('pair_key', name=op.f('uq_dm_conversations_pair_key'))
    )
    op.create_table('federation_events',
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('origin_domain', sa.String(length=253), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['origin_domain'], ['instances.domain'], name=op.f('fk_federation_events_origin_domain_instances')),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_federation_events'))
    )
    op.create_table('peer_keys',
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('key_id', sa.String(length=64), nullable=False),
    sa.Column('public_key', sa.LargeBinary(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['domain'], ['instances.domain'], name=op.f('fk_peer_keys_domain_instances'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('domain', 'key_id', name=op.f('pk_peer_keys'))
    )
    op.create_table('users',
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('avatar_hash', sa.String(length=128), nullable=True),
    sa.Column('banner_hash', sa.String(length=128), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profile_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('origin_domain', sa.String(length=253), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("username ~ '^[a-z0-9_.]{2,32}$'", name=op.f('ck_users_username_format')),
    sa.CheckConstraint('NOT is_local OR (password_hash IS NOT NULL AND email IS NOT NULL)', name=op.f('ck_users_local_auth_fields')),
    sa.ForeignKeyConstraint(['origin_domain', 'is_local'], ['instances.domain', 'instances.is_self'], name='fk_users_origin_locality_instances'),
    sa.PrimaryKeyConstraint('id', 'origin_domain', name=op.f('pk_users')),
    sa.UniqueConstraint('id', 'origin_domain', 'is_local', name='uq_users_ref_locality')
    )
    op.create_index('uq_users_local_email', 'users', [sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('is_local AND email IS NOT NULL'))
    op.create_index('uq_users_username_origin', 'users', [sa.literal_column('lower(username)'), 'origin_domain'], unique=True)
    op.create_table('auth_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_domain', sa.String(length=253), nullable=False),
    sa.Column('user_is_local', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('user_is_local', name=op.f('ck_auth_events_auth_events_user_is_local')),
    sa.ForeignKeyConstraint(['user_id', 'user_domain', 'user_is_local'], ['users.id', 'users.origin_domain', 'users.is_local'], name='fk_auth_events_local_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auth_events'))
    )
    op.create_table('dm_participants',
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_domain', sa.String(length=253), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_domain', sa.String(length=253), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id', 'conversation_domain'], ['dm_conversations.id', 'dm_conversations.origin_domain'], name=op.f('fk_dm_participants_conversation_id_conversation_domain_dm_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'user_domain'], ['users.id', 'users.origin_domain'], name=op.f('fk_dm_participants_user_id_user_domain_users')),
    sa.PrimaryKeyConstraint('conversation_id', 'conversation_domain', 'user_id', 'user_domain', name=op.f('pk_dm_participants'))
    )
    op.create_table('federation_outbox',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('destination', sa.String(length=253), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['federation_events.event_id'], name=op.f('fk_federation_outbox_event_id_federation_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_federation_outbox')),
    sa.UniqueConstraint('destination', 'event_id', name=op.f('uq_federation_outbox_destination_event_id'))
    )
    op.create_index('ix_federation_outbox_delivery', 'federation_outbox', ['destination', 'status', 'next_retry_at'], unique=False)
    op.create_table('guilds',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('icon_hash', sa.String(length=128), nullable=True),
    sa.Column('banner_hash', sa.String(length=128), nullable=True),
    sa.Column('owner_id', sa.BigInteger(), nullable=False),
    sa.Column('owner_domain', sa.String(length=253), nullable=False),
    sa.Column('next_event_seq', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('last_event_seq', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('sync_status', sa.String(length=16), server_default='ready', nullable=False),
    sa.Column('permission_generation', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('unavailable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('origin_domain', sa.String(length=253), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("sync_status IN ('ready','syncing','stale','failed')", name=op.f('ck_guilds_sync_status')),
    sa.ForeignKeyConstraint(['origin_domain'], ['instances.domain'], name=op.f('fk_guilds_origin_domain_instances')),
    sa.ForeignKeyConstraint(['owner_id', 'owner_domain'], ['users.id', 'users.origin_domain'], name=op.f('fk_guilds_owner_id_owner_domain_users')),
    sa.PrimaryKeyConstraint('id', 'origin_domain', name=op.f('pk_guilds'))
    )
    op.create_table('one_time_tokens',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_domain', sa.String(length=253), nullable=False),
    sa.Column('user_is_local', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('user_is_local', name=op.f('ck_one_time_tokens_one_time_tokens_user_is_local')),
    sa.ForeignKeyConstraint(['user_id', 'user_domain', 'user_is_local'], ['users.id', 'users.origin_domain', 'users.is_local'], name='fk_one_time_tokens_local_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_one_time_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_one_time_tokens_token_hash'))
    )
    op.create_table('recovery_codes',
    sa.Column('code_hash', sa.LargeBinary(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_domain', sa.String(length=253), nullable=False),
    sa.Column('user_is_local', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('user_is_local', name=op.f('ck_recovery_codes_recovery_codes_user_is_local')),
    sa.ForeignKeyConstraint(['user_id', 'user_domain', 'user_is_local'], ['users.id', 'users.origin_domain', 'users.is_local'], name='fk_recovery_codes_local_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'user_domain', 'code_hash', name=op.f('pk_recovery_codes'))
    )
    op.create_table('relationships',
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('target_domain', sa.String(length=253), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_domain', sa.String(length=253), nullable=False),
    sa.Column('user_is_local', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("type IN ('friend','pending_in','pending_out','blocked')", name=op.f('ck_relationships_relationship_type')),
    sa.CheckConstraint('(user_id, user_domain) <> (target_id, target_domain)', name=op.f('ck_relationships_not_self_relationship')),
    sa.CheckConstraint('user_is_local', name=op.f('ck_relationships_relationships_user_is_local')),
    sa.ForeignKeyConstraint(['target_id', 'target_domain'], ['users.id', 'users.origin_domain'], name=op.f('fk_relationships_target_id_target_domain_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'user_domain', 'user_is_local'], ['users.id', 'users.origin_domain', 'users.is_local'], name='fk_relationships_local_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'user_domain', 'target_id', 'target_domain', name=op.f('pk_relationships'))
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('refresh_token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('previous_token_hash', sa.LargeBinary(), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_domain', sa.String(length=253), nullable=False),
    sa.Column('user_is_local', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('user_is_local', name=op.f('ck_sessions_sessions_user_is_local')),
    sa.ForeignKeyConstraint(['user_id', 'user_domain', 'user_is_local'], ['users.id', 'users.origin_domain', 'users.is_local'], name='fk_sessions_local_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_table('user_settings',
    sa.Column('locale', sa.String(length=16), server_default='en-US', nullable=False),
    sa.Column('theme', sa.String(length=16), server_default='system', nullable=False),
    sa.Column('dm_privacy', sa.String(length=16), server_default='shared_guild', nullable=False),
    sa.Column('notification_settings', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_domain', sa.String(length=253), nullable=False),
    sa.Column('user_is_local', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("dm_privacy IN ('everyone','shared_guild','friends')", name=op.f('ck_user_settings_dm_privacy_value')),
    sa.CheckConstraint('user_is_local', name=op.f('ck_user_settings_user_settings_user_is_local')),
    sa.ForeignKeyConstraint(['user_id', 'user_domain', 'user_is_local'], ['users.id', 'users.origin_domain', 'users.is_local'], name='fk_user_settings_local_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'user_domain', name=op.f('pk_user_settings'))
    )
    op.create_table('user_storage_usage',
    sa.Column('bytes_used', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('pending_bytes', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_domain', sa.String(length=253), nullable=False),
    sa.Column('user_is_local', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('bytes_used >= 0 AND pending_bytes >= 0', name=op.f('ck_user_storage_usage_nonnegative_usage')),
    sa.CheckConstraint('user_is_local', name=op.f('ck_user_storage_usage_user_storage_usage_user_is_local')),
    sa.ForeignKeyConstraint(['user_id', 'user_domain', 'user_is_local'], ['users.id', 'users.origin_domain', 'users.is_local'], name='fk_user_storage_usage_local_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'user_domain', name=op.f('pk_user_storage_usage'))
    )
    op.create_table('audit_log_entries',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_domain', sa.String(length=253), nullable=False),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_domain', sa.String(length=253), nullable=False),
    sa.Column('action_type', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_ref', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id', 'guild_domain'], ['guilds.id', 'guilds.origin_domain'], name=op.f('fk_audit_log_entries_guild_id_guild_domain_guilds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log_entries'))
    )
    op.create_index('ix_audit_log_guild_id_desc', 'audit_log_entries', ['guild_id', 'guild_domain', 'id'], unique=False)
    op.create_table('bans',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_domain', sa.String(length=253), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_domain', sa.String(length=253), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('actor_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_domain', sa.String(length=253), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id', 'guild_domain'], ['guilds.id', 'guilds.origin_domain'], name=op.f('fk_bans_guild_id_guild_domain_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'user_domain'], ['users.id', 'users.origin_domain'], name=op.f('fk_bans_user_id_user_domain_users')),
    sa.PrimaryKeyConstraint('guild_id', 'guild_domain', 'user_id', 'user_domain', name=op.f('pk_bans'))
    )
    op.create_table('channels',
    sa.Column('guild_id', sa.BigInteger(), nullable=True),
    sa.Column('guild_domain', sa.String(length=253), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=1024), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_domain', sa.String(length=253), nullable=True),
    sa.Column('rate_limit_per_user', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_floor_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('origin_domain', sa.String(length=253), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(guild_id IS NULL) = (guild_domain IS NULL)', name=op.f('ck_channels_guild_ref_complete')),
    sa.CheckConstraint('type IN (0,1,2,4,5)', name=op.f('ck_channels_channel_type')),
    sa.ForeignKeyConstraint(['guild_id', 'guild_domain'], ['guilds.id', 'guilds.origin_domain'], name=op.f('fk_channels_guild_id_guild_domain_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id', 'parent_domain'], ['channels.id', 'channels.origin_domain'], name=op.f('fk_channels_parent_id_parent_domain_channels'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', 'origin_domain', name=op.f('pk_channels'))
    )
    op.create_index('ix_channels_guild_position', 'channels', ['guild_id', 'guild_domain', 'position'], unique=False)
    op.create_table('emojis',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_domain', sa.String(length=253), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('animated', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('creator_domain', sa.String(length=253), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('origin_domain', sa.String(length=253), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id', 'guild_domain'], ['guilds.id', 'guilds.origin_domain'], name=op.f('fk_emojis_guild_id_guild_domain_guilds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'origin_domain', name=op.f('pk_emojis')),
    sa.UniqueConstraint('guild_id', 'guild_domain', 'name', name=op.f('uq_emojis_guild_id_guild_domain_name'))
    )
    op.create_table('guild_events',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_domain', sa.String(length=253), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('envelope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id', 'guild_domain'], ['guilds.id', 'guilds.origin_domain'], name=op.f('fk_guild_events_guild_id_guild_domain_guilds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'guild_domain', 'seq', name=op.f('pk_guild_events')),
    sa.UniqueConstraint('event_id', name=op.f('uq_guild_events_event_id'))
    )
    op.create_index('ix_guild_events_created_at', 'guild_events', ['created_at'], unique=False)
    op.create_table('guild_members',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_domain', sa.String(length=253), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_domain', sa.String(length=253), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timeout_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('voice_flags', sa.Integer(), server_default='0', nullable=False),
    sa.Column('member_version', sa.BigInteger(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id', 'guild_domain'], ['guilds.id', 'guilds.origin_domain'], name=op.f('fk_guild_members_guild_id_guild_domain_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'user_domain'], ['users.id', 'users.origin_domain'], name=op.f('fk_guild_members_user_id_user_domain_users')),
    sa.PrimaryKeyConstraint('guild_id', 'guild_domain', 'user_id', 'user_domain', name=op.f('pk_guild_members'))
    )
    op.create_index('ix_guild_members_user', 'guild_members', ['user_id', 'user_domain'], unique=False)
    op.create_table('invites',
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_domain', sa.String(length=253), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=True),
    sa.Column('channel_domain', sa.String(length=253), nullable=True),
    sa.Column('inviter_id', sa.BigInteger(), nullable=False),
    sa.Column('inviter_domain', sa.String(length=253), nullable=False),
    sa.Column('uses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(code) = 8', name=op.f('ck_invites_code_length')),
    sa.ForeignKeyConstraint(['guild_id', 'guild_domain'], ['guilds.id', 'guilds.origin_domain'], name=op.f('fk_invites_guild_id_guild_domain_guilds'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inviter_id', 'inviter_domain'], ['users.id', 'users.origin_domain'], name=op.f('fk_invites_inviter_id_inviter_domain_users')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_invites'))
    )
    op.create_table('roles',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_domain', sa.String(length=253), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color', sa.Integer(), server_default='0', nullable=False),
    sa.Column('permissions', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('hoist', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('mentionable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('origin_domain', sa.String(length=253), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['guild_id', 'guild_domain'], ['guilds.id', 'guilds.origin_domain'], name=op.f('fk_roles_guild_id_guild_domain_guilds'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'origin_domain', name=op.f('pk_roles'))
    )
    op.create_index('ix_roles_guild_position', 'roles', ['guild_id', 'guild_domain', 'position'], unique=False)
    op.create_table('channel_overwrites',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_domain', sa.String(length=253), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('target_domain', sa.String(length=253), nullable=False),
    sa.Column('target_type', sa.String(length=8), nullable=False),
    sa.Column('allow', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('deny', sa.BigInteger(), server_default='0', nullable=False),
    sa.CheckConstraint("target_type IN ('role','member')", name=op.f('ck_channel_overwrites_target_type')),
    sa.ForeignKeyConstraint(['channel_id', 'channel_domain'], ['channels.id', 'channels.origin_domain'], name=op.f('fk_channel_overwrites_channel_id_channel_domain_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', 'channel_domain', 'target_id', 'target_domain', 'target_type', name=op.f('pk_channel_overwrites'))
    )
    op.create_table('member_roles',
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_domain', sa.String(length=253), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_domain', sa.String(length=253), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('role_domain', sa.String(length=253), nullable=False),
    sa.ForeignKeyConstraint(['guild_id', 'guild_domain', 'user_id', 'user_domain'], ['guild_members.guild_id', 'guild_members.guild_domain', 'guild_members.user_id', 'guild_members.user_domain'], name=op.f('fk_member_roles_guild_id_guild_domain_user_id_user_domain_guild_members'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id', 'role_domain'], ['roles.id', 'roles.origin_domain'], name=op.f('fk_member_roles_role_id_role_domain_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('guild_id', 'guild_domain', 'user_id', 'user_domain', 'role_id', 'role_domain', name=op.f('pk_member_roles'))
    )
    op.create_table('messages',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_domain', sa.String(length=253), nullable=False),
    sa.Column('author_id', sa.BigInteger(), nullable=False),
    sa.Column('author_domain', sa.String(length=253), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('e2ee', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('message_type', sa.Integer(), server_default='0', nullable=False),
    sa.Column('flags', sa.Integer(), server_default='0', nullable=False),
    sa.Column('client_nonce', sa.String(length=64), nullable=True),
    sa.Column('referenced_message_id', sa.BigInteger(), nullable=True),
    sa.Column('referenced_message_domain', sa.String(length=253), nullable=True),
    sa.Column('mention_user_refs', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('origin_domain', sa.String(length=253), nullable=False),
    sa.ForeignKeyConstraint(['author_id', 'author_domain'], ['users.id', 'users.origin_domain'], name=op.f('fk_messages_author_id_author_domain_users')),
    sa.ForeignKeyConstraint(['channel_id', 'channel_domain'], ['channels.id', 'channels.origin_domain'], name=op.f('fk_messages_channel_id_channel_domain_channels')),
    sa.PrimaryKeyConstraint('id', 'origin_domain', name=op.f('pk_messages')),
    postgresql_partition_by='RANGE (id)'
    )
    op.create_index('ix_messages_author_id_desc', 'messages', ['author_id', 'author_domain', 'id'], unique=False)
    op.create_index('ix_messages_author_nonce', 'messages', ['author_id', 'author_domain', 'client_nonce'], unique=False, postgresql_where=sa.text('client_nonce IS NOT NULL'))
    op.create_index('ix_messages_channel_id_desc', 'messages', ['channel_id', 'channel_domain', 'id'], unique=False)
    op.create_index('ix_messages_id_brin', 'messages', ['id'], unique=False, postgresql_using='brin')
    # Deterministic initial coverage from the Kaede epoch through September 2026
    # (the current month plus two). The partitions.ensure job extends this horizon.
    _create_message_partition(2026, 1, 2026, 2)
    _create_message_partition(2026, 2, 2026, 3)
    _create_message_partition(2026, 3, 2026, 4)
    _create_message_partition(2026, 4, 2026, 5)
    _create_message_partition(2026, 5, 2026, 6)
    _create_message_partition(2026, 6, 2026, 7)
    _create_message_partition(2026, 7, 2026, 8)
    _create_message_partition(2026, 8, 2026, 9)
    _create_message_partition(2026, 9, 2026, 10)
    op.create_table('read_states',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_domain', sa.String(length=253), nullable=False),
    sa.Column('last_message_id', sa.BigInteger(), nullable=True),
    sa.Column('mention_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_domain', sa.String(length=253), nullable=False),
    sa.Column('user_is_local', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('user_is_local', name=op.f('ck_read_states_read_states_user_is_local')),
    sa.ForeignKeyConstraint(['channel_id', 'channel_domain'], ['channels.id', 'channels.origin_domain'], name=op.f('fk_read_states_channel_id_channel_domain_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'user_domain', 'user_is_local'], ['users.id', 'users.origin_domain', 'users.is_local'], name='fk_read_states_local_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'user_domain', 'channel_id', 'channel_domain', name=op.f('pk_read_states'))
    )
    op.create_table('webhooks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('guild_domain', sa.String(length=253), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_domain', sa.String(length=253), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('avatar_hash', sa.String(length=128), nullable=True),
    sa.Column('token_hash', sa.LargeBinary(), nullable=False),
    sa.Column('creator_id', sa.BigInteger(), nullable=False),
    sa.Column('creator_domain', sa.String(length=253), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id', 'channel_domain'], ['channels.id', 'channels.origin_domain'], name=op.f('fk_webhooks_channel_id_channel_domain_channels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhooks'))
    )
    op.create_table('attachments',
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('message_domain', sa.String(length=253), nullable=True),
    sa.Column('uploader_id', sa.BigInteger(), nullable=False),
    sa.Column('uploader_domain', sa.String(length=253), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('blurhash', sa.String(length=128), nullable=True),
    sa.Column('scan_status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('origin_domain', sa.String(length=253), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scan_status IN ('pending','clean','infected','failed')", name=op.f('ck_attachments_scan_status')),
    sa.ForeignKeyConstraint(['message_id', 'message_domain'], ['messages.id', 'messages.origin_domain'], name=op.f('fk_attachments_message_id_message_domain_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id', 'uploader_domain'], ['users.id', 'users.origin_domain'], name=op.f('fk_attachments_uploader_id_uploader_domain_users')),
    sa.PrimaryKeyConstraint('id', 'origin_domain', name=op.f('pk_attachments'))
    )
    op.create_table('pins',
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('channel_domain', sa.String(length=253), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('message_domain', sa.String(length=253), nullable=False),
    sa.Column('pinned_by_id', sa.BigInteger(), nullable=False),
    sa.Column('pinned_by_domain', sa.String(length=253), nullable=False),
    sa.Column('pinned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id', 'channel_domain'], ['channels.id', 'channels.origin_domain'], name=op.f('fk_pins_channel_id_channel_domain_channels'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id', 'message_domain'], ['messages.id', 'messages.origin_domain'], name=op.f('fk_pins_message_id_message_domain_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pinned_by_id', 'pinned_by_domain'], ['users.id', 'users.origin_domain'], name=op.f('fk_pins_pinned_by_id_pinned_by_domain_users')),
    sa.PrimaryKeyConstraint('channel_id', 'channel_domain', 'message_id', 'message_domain', name=op.f('pk_pins'))
    )
    op.create_table('reactions',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('message_domain', sa.String(length=253), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_domain', sa.String(length=253), nullable=False),
    sa.Column('emoji_key', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id', 'message_domain'], ['messages.id', 'messages.origin_domain'], name=op.f('fk_reactions_message_id_message_domain_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id', 'user_domain'], ['users.id', 'users.origin_domain'], name=op.f('fk_reactions_user_id_user_domain_users')),
    sa.PrimaryKeyConstraint('message_id', 'message_domain', 'user_id', 'user_domain', 'emoji_key', name=op.f('pk_reactions'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reactions')
    op.drop_table('pins')
    op.drop_table('attachments')
    op.drop_table('webhooks')
    op.drop_table('read_states')
    op.drop_index('ix_messages_id_brin', table_name='messages', postgresql_using='brin')
    op.drop_index('ix_messages_channel_id_desc', table_name='messages')
    op.drop_index('ix_messages_author_nonce', table_name='messages', postgresql_where=sa.text('client_nonce IS NOT NULL'))
    op.drop_index('ix_messages_author_id_desc', table_name='messages')
    op.drop_table('messages')
    op.drop_table('member_roles')
    op.drop_table('channel_overwrites')
    op.drop_index('ix_roles_guild_position', table_name='roles')
    op.drop_table('roles')
    op.drop_table('invites')
    op.drop_index('ix_guild_members_user', table_name='guild_members')
    op.drop_table('guild_members')
    op.drop_index('ix_guild_events_created_at', table_name='guild_events')
    op.drop_table('guild_events')
    op.drop_table('emojis')
    op.drop_index('ix_channels_guild_position', table_name='channels')
    op.drop_table('channels')
    op.drop_table('bans')
    op.drop_index('ix_audit_log_guild_id_desc', table_name='audit_log_entries')
    op.drop_table('audit_log_entries')
    op.drop_table('user_storage_usage')
    op.drop_table('user_settings')
    op.drop_table('sessions')
    op.drop_table('relationships')
    op.drop_table('recovery_codes')
    op.drop_table('one_time_tokens')
    op.drop_table('guilds')
    op.drop_index('ix_federation_outbox_delivery', table_name='federation_outbox')
    op.drop_table('federation_outbox')
    op.drop_table('dm_participants')
    op.drop_table('auth_events')
    op.drop_index('uq_users_username_origin', table_name='users')
    op.drop_index('uq_users_local_email', table_name='users', postgresql_where=sa.text('is_local AND email IS NOT NULL'))
    op.drop_table('users')
    op.drop_table('peer_keys')
    op.drop_table('federation_events')
    op.drop_table('dm_conversations')
    op.drop_index('ix_remote_media_cache_eviction', table_name='remote_media_cache')
    op.drop_table('remote_media_cache')
    op.drop_index('uq_instances_single_self', table_name='instances', postgresql_where=sa.text('is_self'))
    op.drop_table('instances')
    op.drop_table('instance_blocks')
    op.drop_table('federation_inbox')
    # ### end Alembic commands ###
