from enum import IntEnum

PROTOCOL_VERSION = 1


class GatewayOp(IntEnum):
    DISPATCH = 0
    HEARTBEAT = 1
    IDENTIFY = 2
    PRESENCE_UPDATE = 3
    VOICE_STATE_UPDATE = 4
    RESUME = 6
    RECONNECT = 7
    REQUEST_MEMBERS = 8
    INVALID_SESSION = 9
    HELLO = 10
    HEARTBEAT_ACK = 11
    SUBSCRIBE_MEMBER_LIST = 12


EVENT_NAMES = (
    "READY",
    "RESUMED",
    "MESSAGE_CREATE",
    "MESSAGE_UPDATE",
    "MESSAGE_DELETE",
    "MESSAGE_SEND_REJECTED",
    "MESSAGE_DELIVERY_UPDATE",
    "ATTACHMENT_UPDATE",
    "DM_OPEN_REJECTED",
    "CHANNEL_CREATE",
    "CHANNEL_UPDATE",
    "CHANNEL_DELETE",
    "CHANNEL_ACCESS_GRANTED",
    "CHANNEL_ACCESS_REVOKED",
    "CHANNEL_PERMISSION_UPDATE",
    "GUILD_CREATE",
    "GUILD_UPDATE",
    "GUILD_DELETE",
    "GUILD_ROLE_CREATE",
    "GUILD_ROLE_UPDATE",
    "GUILD_ROLE_DELETE",
    "GUILD_EMOJI_CREATE",
    "GUILD_EMOJI_DELETE",
    "GUILD_MEMBER_ADD",
    "GUILD_MEMBER_UPDATE",
    "GUILD_MEMBER_REMOVE",
    "GUILD_MEMBERS_CHUNK",
    "GUILD_MEMBER_LIST_UPDATE",
    "GUILD_AVAILABILITY_UPDATE",
    "GUILD_NAVIGATION_UPDATE",
    "GUILD_HISTORY_SYNC_UPDATE",
    "PRESENCE_UPDATE",
    "TYPING_START",
    "VOICE_STATE_UPDATE",
    "VOICE_CHANNEL_MOVE",
    "VOICE_TOKEN",
    "READ_STATE_UPDATE",
    "USER_UPDATE",
    "FEDERATION_PEER_STATUS",
    "CALL_CREATE",
    "CALL_RING",
    "CALL_ACCEPT",
    "CALL_DECLINE",
    "CALL_END",
)
